services:
  - type: web
    name: gooey-theatergwd
    runtime: python
    rootDir: gooey
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py --host 0.0.0.0 --port $PORT --no-browser
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DEMO_MODE
        value: "true"
    plan: free
